<a href="https://colab.research.google.com/github/liberato10/IntroToNumpayArrays/blob/main/IntroToNumpyipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
price = [2, 1, 10]
type(price)

list

In [2]:
quantity = [17, 40, 1]
type(quantity)

list

In [ ]:
# price * quantity

In [ ]:
import numpy as np

In [ ]:
price_array = np.array(price)
quantity_array = np.array(quantity)
type(price_array)

numpy.ndarray

In [ ]:
price_array * quantity_array

array([34, 40, 10])

In [ ]:
cost_array = np.array([0.25, 0.50, 5.00])

In [ ]:
profit_array = price_array - cost_array
print(profit_array)


[1.75 0.5  5.  ]


In [ ]:
profit_array > 2.00


array([False, False,  True])

In [ ]:
price_array = price_array + [7]
print(price_array)


[ 9  8 17]


In [ ]:
# Just fixing the mistake
price_array = price_array - [7]
# The proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)


[ 2  1 10  7]


In [ ]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)



[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [ ]:
print(price_array.dtype)


float64


In [ ]:
price_array = np.delete(price_array, -1)
print(price_array)


[ 2.   1.  10.   7.   4.5  3.   4. ]


In [ ]:
price_array[2] = 12
print(price_array)


[ 2.   1.  12.   7.   4.5  3.   4. ]
